# Generated by Django 5.0.2 on 2024-02-27 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowhub', '0004_alter_articles_category_alter_comment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='articles',
            new_name='article',
        ),
    ]
