# Generated by Django 5.0.2 on 2024-03-02 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowhub', '0007_alter_services_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
    ]
