# Generated by Django 5.0.2 on 2024-03-05 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowhub', '0009_articles_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='content',
            field=models.TextField(default=datetime.datetime(2024, 3, 5, 15, 39, 37, 992305, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
